server:
  port: 9086
spring:
  application:
    name: charer-system
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    #        use_sql_comments: false
    #        session_factory:
    #          statement_inspector: com.obast.charer.data.interceptor.JpaStatementInterceptor
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/charer-open?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      #idle-timeout: 30000 # 经过idle-timeout时间如果连接还处于空闲状态, 该连接会被回收
      #min-idle: 3 # 池中维护的最小空闲连接数, 默认为 10 个
      #max-pool-size: 50 # 池中最大连接数, 包括闲置和使用中的连接, 默认为 10 个
      max-lifetime: 0 # 如果一个连接超过了时长，且没有被使用, 连接会被回收
      #is-auto-commit: true
  #   ============mysql配置结束============>>

  #<<================es时序数据配置开始===============
  elasticsearch:
    #embedded:
    #  # 是否启用内部es
    #  enabled: false
    #  port: 9200
    uris: http://127.0.0.1:9200
    username:
    password:
    connection-timeout: 10s
  #================es时序数据配置结束===============>>

  #<<===========tdengine时序数据库配置开始============
  #  td-datasource:
  #    url: jdbc:TAOS-RS://127.0.0.1:6041/obast?timezone=UTC-8&charset=UTF-8&locale=en_US.UTF-8
  #    username: root
  #    password: taosdata
  #    driverClassName: com.taosdata.jdbc.rs.RestfulDriver
  #===========tdengine时序数据库配置开始============>>
  redis:
    #使用内置redis的配置
    #embedded:
    #  enabled: false
    #host: redis
    host: 127.0.0.1
    port: 6379
    database: 1

  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
#  profiles:
#    active: dev


logging:
  level:
    #    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.engine.QueryParameters: DEBUG
    org.hibernate.engine.query.HQLQueryPlan: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
    net.ttddyy.dsproxy.listener: debug
    com.vladmihalcea.hibernate: error
    '[Hibernate Types]': error

  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level - %msg%n'

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: jiufu-system
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

captcha:
  enable: false
  # 页面 <参数设置> 可开启关闭 验证码校验
  # 验证码类型 math 数组计算 char 字符验证
  type: CHAR
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: CIRCLE
  # 数字验证码位数
  numberLength: 1
  # 字符验证码长度
  charLength: 4

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 50
    # 密码锁定时间（默认10分钟）
    lockTime: 10

websocket:
  enabled: true
  path: /websocket
  allowedOrigins: '*'

charer:
  baseUrl: 'http://192.168.3.61'
  # 多租户
  tenant:
    enable: true
  # 代理商
  agent:
    enable: true
  # 合作商
  dealer:
    enable: true
  #是否开启分润
  profit:
    enabled: true

  #系统模块
  system:
    i18n:
      #默认语言
      language: zh_CN
      multiple: false
      locales:
        - locale: zh_CN
          timezone: GMT+8
          date-format: 'yyyy-MM-dd HH:mm:ss'
        - locale: en_US
          timezone: GMT+8
          date-format: 'yyyy-MM-dd HH:mm:ss'
        - locale: ru_RU
          timezone: GMT+8
          date-format: 'yyyy-MM-dd HH:mm:ss'

  #openapi模块
  openapi:
    i18n:
      #默认语言
      language: zh_CN
      multiple: false
      locales:
        - locale: zh_CN
          timezone: GMT+8
          date-format: 'yyyy-MM-dd HH:mm:ss'
        - locale: en_US
          timezone: GMT+8
          date-format: 'yyyy-MM-dd HH:mm:ss'
        - locale: ru_RU
          timezone: GMT+8
          date-format: 'yyyy-MM-dd HH:mm:ss'