server:
  port: 9088
spring:
  application:
    name: charer-plugin
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/charer-open?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      max-lifetime: 0

  elasticsearch:
    uris: http://127.0.0.1:9200
    username:
    password:
    connection-timeout: 10s

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1

  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.engine.QueryParameters: DEBUG
    org.hibernate.engine.query.HQLQueryPlan: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
    net.ttddyy.dsproxy.listener: debug
    com.vladmihalcea.hibernate: error
    '[Hibernate Types]': error

  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level - %msg%n'

plugin:
  runMode: prod
  mainPackage: com.obast.charer
  pluginPath:
    - /Users/chuan/Desktop/java/charer/charer-cloud/data/plugins/