server:
  port: 9087
spring:
  application:
    name: charer-openapi
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/charer-open?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 'Chuan811025@'
    hikari:
      connection-timeout: 30000
      max-lifetime: 0

  elasticsearch:
    uris: http://127.0.0.1:9200
    username:
    password:
    connection-timeout: 10s

  redis:
    host: 127.0.0.1
    port: 6379
    database: 2

  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.engine.QueryParameters: DEBUG
    org.hibernate.engine.query.HQLQueryPlan: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
    net.ttddyy.dsproxy.listener: debug
    com.vladmihalcea.hibernate: error
    '[Hibernate Types]': error

  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level - %msg%n'


sa-token:
  # token名称 (同时也是cookie名称)
  token-name: x-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


charer:
  #系统模块
  system:
    baseUrl: 'http://192.168.3.61'

  #openapi模块
  openapi:
    baseUrl: 'http://192.168.3.61'